# Generated by Django 3.0.7 on 2020-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='lectures',
            field=models.CharField(choices=[('CSE341', 'CSE341'), ('CSE312', 'CSE312'), ('CSE396', 'CSE396')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='general',
            name='name',
            field=models.CharField(choices=[('Rumeysa KARAKAVAK', 'Rumeysa KARAKAVAK'), ('Busra Nur ALTUNBAS', 'Busra Nur ALTUNBAS'), ('Esra CERAN', 'Esra CERAN')], max_length=300, null=True),
        ),
    ]
