# Generated by Django 3.0.7 on 2020-07-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDashboard', '0002_auto_20200702_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='linkName',
        ),
        migrations.AddField(
            model_name='general',
            name='photo',
            field=models.ImageField(default='img.jpg', upload_to=''),
        ),
    ]
