# Generated by Django 3.0.7 on 2020-07-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterDashboard', '0003_auto_20200706_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='general',
            name='number',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='general',
            name='photo',
            field=models.ImageField(default='def.png', upload_to=''),
        ),
    ]
